package thredds.server.metadata.bean;

/**
 * NetCDFAttributeType
 * Author: dneufeld Date: Jun 14, 2010
 * <p/>
 */
public enum NetCDFAttributeType {
	
	GEOSPATIAL_LAT_MIN,
	GEOSPATIAL_LAT_MAX,
	GEOSPATIAL_LON_MIN,
	GEOSPATIAL_LON_MAX,
	
	GEOSPATIAL_LAT_UNITS,
	GEOSPATIAL_LAT_RES,
	GEOSPATIAL_LON_UNITS,
	GEOSPATIAL_LON_RES,
	
	GEOSPATIAL_VERTICAL_MIN,
	GEOSPATIAL_VERTICAL_MAX,
	GEOSPATIAL_VERTICAL_UNITS,
	GEOSPATIAL_VERTICAL_RES,
	GEOSPATIAL_VERTICAL_POS,
	
	TIME_COVERAGE_START,
	TIME_COVERAGE_END,
	TIME_COVERAGE_UNITS,
	TIME_COVERAGE_DURATION,
	TIME_COVERAGE_RES
	
}
